export const ROUTES = {
  home: "/",
  services: "/services",
  solutions: "/solutions",
  industries: "/industries",
  technologies: "/technologies",
  projects: "/projects",
  careers: "/careers",
  about: "/about",
  blog: "/blog",
  contact: "/contact",
  booking: "/book-consultation",
  clientLogin: "/client-login",
  support: "/support",
  status: "/status",
  privacyPolicy: "/privacy-policy",
  termsConditions: "/terms",
  cookiePolicy: "/cookie-policy",
  gdprNotice: "/gdpr-notice",
} as const
